apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disaster-response
  namespace: disaster-response
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
spec:
  ingressClassName: nginx
  rules:
    - host: disaster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: 80
