apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: disaster-response
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - kafka.yaml
  - kafka-topics-job.yaml
  - qdrant.yaml
  - incident-service.yaml
  - coordination-service.yaml
  - notification-service.yaml
  - rag-service.yaml
  - ai-orchestrator.yaml
  - api-gateway.yaml
  - ingestion-service.yaml
  - frontend-web.yaml
  - ingress.yaml
