apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: disaster-response
resources:
  - namespace.yaml
  - monitoring-secrets.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - kafka-exporter.yaml
  - grafana-datasource.yaml
  - grafana-dashboard-provider.yaml
  - grafana-dashboard-platform.yaml
  - grafana.yaml
  - ingress.yaml
